### PR TITLE
Update development and CI configurations

### LINKED ISSUE #92: Circular dependencies on tests
plone.app.widgets [depends on plone.app.event](https://github.com/plone/plone.app.widgets/blob/master/setup.py#L52) which [depends on plone.app.widgets](https://github.com/plone/plone.app.event/blob/master/setup.py#L104).

When running tests, `bin/test` pulls in the 1.7.0 release, even though I'm working in the master branch.  Which defeats the purpose of testing.

   > grep widget bin/test
   '/home/hvelarde/.buildout/eggs/plone.app.widgets-1.7.0-py2.7.egg',

### PR DESCRIPTION
**Pull request by hvelarde**
* Update bootstrap.py
* Remove dependency on unittest2
* Update development and CI configurations
* Remove circular dependencies (partially fixes #92)

Please review an comment, some of these changes must be applied to 2.x branch also.

There are a couple of failing tests that I don't know how to fix.

Refs. #94

### CODE REVIEW

**Comment by hvelarde** [comment]
@vangheem @thet one more porting the changes on 1.x

**Comment by vangheem** [comment]
Feel free to merge yourself. I'm not working on plone.app.widgets much anymore as it's all been ported to plone 5 now.

**Comment by thet** [comment]
wouldn't these changes better applied to the 1.x branch? current master's purpose is to make itself obsolete. @hvelarde

**Comment by hvelarde** [comment]
@thet reverted; changes ar3e already on 1.x

**Comment by gforcada** [comment]
@thet given your comment, wouldn't make sense to warn about this "will be obsolete on 5" on the README itself?

**Comment by thet** [comment]
I agree, there should be a  note like this. or like "In Plone 5, plone.app.widgets is obsolete because it's merged into plone.app.z3cform.".

**Pull request merged**
