### PR TITLE
fix commented out syntax (was a invalid heading)

### PR DESCRIPTION
**Pull request by pbauer**
That creates errrors with newest versions of robotframework:

```
[ ERROR ] Error in file '/Users/pbauer/.cache/buildout/eggs/plone.app.widgets-3.0.0-py3.7.egg/plone/app/widgets/tests/robot/test_querystring_widget.robot': Unrecognized table header 'Comment out until we can figure out what is wrong with this test...'. Available headers for data: 'Setting(s)', 'Variable(s)', 'Test Case(s)', 'Task(s)' and 'Keyword(s)'. Use 'Comment(s)' to embedded additional data.
```

### CODE REVIEW

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
the test got uncommented and fixed here #214

**Pull request closed without merging**
