### PR TITLE
Remove GS profile pointing to non existing directory.

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by gforcada** [comment]
@jensens although the tests *passed* there are quite a lot of errors on the console output: https://jenkins.plone.org/job/pull-request-5.2-3.6/129/console

I wonder why this is not reported as errors... :confused:

**Comment by jensens** [comment]
Leftovers need to be removed here 
https://github.com/plone/plone.app.relationfield/pull/25
and here
https://github.com/plone/plone.app.collection/pull/53

**Comment by jensens** [comment]
Also - but outside coredev - `plone.app.standardtiles` loads it in its https://github.com/plone/plone.app.standardtiles/blob/f13db57dd9a443d108efdde65f75a28a6b49d832/plone/app/standardtiles/testing.py#L165

**Comment by jensens** [comment]
PR here https://github.com/plone/plone.app.standardtiles/pull/92

**Pull request merged**
