### PR TITLE
Fixed timing issue in robot tests.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Well, that is what I hope.
Sample error link in a pull request job:
http://jenkins.plone.org/job/pull-request-5.0/841/robot/report/robot_log.html#s1-s33-t1

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Travis is completely broken. I had started on some fixes on this branch, but reverted those and will continue that on a different branch.
For this pull request, the only question is whether Jenkins passes.

**Comment by mauritsvanrees** [comment]
Travis is utterly broken, due to no fault of this pull request. See pull request #130 for that.

Jenkins passes, which is the interesting part. Ready for review and merge.

**Comment by mauritsvanrees** [comment]
For the record, I have merged my own pull request. Yes, bad form, but for such a small change I think it is okay. The pull request was more to let Jenkins confirm that all is well.

**Comment by vangheem** [comment]
No worries. Thank you.

**Pull request merged**
