### PR TITLE
Added FileUpload widget for NamedFiles.

### PR DESCRIPTION
**Pull request by athomerson**
This widget uses the 'Upload' pattern from mockup. It can be used for both single and multiple file uploads. Tests are written. I will submit a matching pull request on mockup.

### CODE REVIEW

**Comment by thet** [comment]
Sorry for this very late answer!
Wasn't there a discussion already? I thought your pull request was already discussed.
I guess, this pull-request is still relevant, isn't it? How is this different from https://github.com/plone/plone.app.widgets/pull/80 ?

**Comment by thet** [comment]
Related: https://github.com/plone/plone.app.widgets/issues/78

**Comment by thet** [comment]
Oh, I guess the discussion was done on the mockup repo and it was regarding dropzone vs blueimp. Are you using the in this pull-request the blueimp library or mockup's upload pattern, which uses dropzone?

**Comment by athomerson** [comment]
This one uses dropzone. It doesn't use TUS because I couldn't figure out how to upload files automatically with it

**Comment by vangheem** [comment]
This was never merged unfortunately because it broke other things: https://github.com/plone/mockup/pull/447

https://github.com/plone/mockup/pull/449

I'll try and think about it more--we need a decent file widget.

Sorry, it was breaking the normal use of the widget so we couldn't merge and then I never got around to looking into it more.

**Comment by athomerson** [comment]
I didn't see what other things it broke. I must not have run all the right tests. I could put the changes into a separate pattern.

**Comment by vangheem** [comment]
If you aren't too bothered, could you update the pull requests again? I'll play with them and attempt merging again.

Don't make the changes in another package.

Also, notice, for plone 5, the widgets got integrated into plone.app.z3cform and other packages. plone.app.widgets is pretty bare in plone 5. You might need to also do a pull request for plone.app.z3cform.

If you're not working/targeting plone 5, I can't port your code to it when the PR is ready.

**Comment by thet** [comment]
@vangheem you mean you can, not can't, or? if not, i can :)

recently we were discussing about a file widget, which can also reuse already uploaded files/images. just saying. maybe another pull request after this one got merged.

**Comment by vangheem** [comment]
Oops, I mean "can".

**Comment by athomerson** [comment]
Okay I've made the changes. I needed to change Mockup, plone.app.widgets and plone.app.z3cform. Do I need to create pull requests for the other packages? I've seen some discussion about using plone.app.drafts but I didn't try to use it. I've used temporary files instead.

**Comment by vangheem** [comment]
Yes, please make pull requests so we can take a look.

**Pull request closed without merging**
