### PR TITLE
get_ajaxselect_options is no longer used in plone.app.z3cform

### PR DESCRIPTION
**Pull request by jensens**
Deprecate it.

Refactor get_relateditems_options to be more specific.

More cleanup would be needed.

### CODE REVIEW

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@gforcada this need to be run together with other PRs and theres still a problem left as I found at my last run.

**Comment by pbauer** [comment]
I saw the same issue as jenkins did during some job: Rendering the relateditems widgets with a previously set value breaks.

```
  File "/home/gitlab-runner/builds/44df7dbf/0/kbo/kbo-buildout/src-mrd/plone.app.z3cform/plone/app/z3cform/widget.py", line 116, in render
    _base_args = self._base_args()
  File "/home/gitlab-runner/builds/44df7dbf/0/kbo/kbo-buildout/src-mrd/plone.app.z3cform/plone/app/z3cform/widget.py", line 599, in _base_args
    field_name,
  File "/home/gitlab-runner/builds/44df7dbf/0/kbo/kbo-buildout/src-mrd/plone.app.widgets/plone/app/widgets/utils.py", line 144, in get_relateditems_options
    'v': value.split(separator)
  File "/home/gitlab-runner/builds/44df7dbf/0/kbo/kbo-buildout/src-mrd/plone.app.vocabularies/plone/app/vocabularies/catalog.py", line 635, in __call__
    parsed = parseQueryString(context, query['criteria'])
TypeError: list indices must be integers, not str
```

**Comment by jensens** [comment]
Yes, I am aware. It's not ready yet.

**Comment by pbauer** [comment]
Looks good to me.

**Comment by jensens** [comment]
5.1 failure see plone/jenkins.plone.org#258 - this is no blocker for merging!

**Pull request merged**
