### PR TITLE
Update mockup in 1.x, to integrate recent (but now fixed) mockup regression in link modal for tinymce

### PR DESCRIPTION
**Pull request by seanupton**
@petschki @thet Does this look reasonable (changes only to 1.x branch)?

I built mockup via $ make bundle-widgets and copied into static/ -- this should include mockup up to https://github.com/plone/mockup/commit/8bafc7eb54e0d34ce72771110c4930c092055621

...and in particular this fix for tinymce link modals: https://github.com/plone/mockup/commit/08188349fb8ccb427a945b2eaff3c072ec5ae670

This seems to fix the link modals in my limited testing.

### CODE REVIEW

**Comment by petschki** [comment]
Strange. I've updated the mockup resources in my pull request. But it's ok for me to update again!

**Comment by seanupton** [comment]
@petschki AFAICT your mockup update was merged on April 5 into 1.x branch, but mockup build was done on [April 4](https://github.com/plone/plone.app.widgets/commit/9b7f40750a1d993c6771961bc622c9f497da2fed), @thet fixed the regression (that you [noted](https://github.com/plone/mockup/commit/dafd2c56fded62f114bf8eb39845ffb026dfa8fa#commitcomment-16966119) on March 20) on [April 5](https://github.com/plone/mockup/commit/08188349fb8ccb427a945b2eaff3c072ec5ae670).

**Comment by petschki** [comment]
Ah ok. Thanks for clarifying.

**Comment by seanupton** [comment]
Folks, closing this PR because we likely should be using mockup 1.x branch in the plone.app.widgets 1.x branch.

But that leaves the plone.app.widgets 1.x branch master in a bit of a tricky (and broken) situation: like my commit, the previous build of mockup from @petschki committed to the 1.x branch of plone.app.widgets was based (AFAICT) on mockup master.  This might create some problems, and I'm not sure if there are specific things that needed backporting into 1.x branch of mockup from mockup/master?

Maybe appropriate solution is to revert back to 1.x branch of mockup as of https://github.com/plone/mockup/commit/a661129385071ef0d5c7a0158957eacf696a45a6 for build here; anybody who wants newer mockup should create another branch?  If this seems sensible, I may take care of reverting mockup build in a distinct pull request to replace the intent of this one.

**Pull request closed without merging**
