### PR TITLE
fix: ensure we have all content for tree query in relateditems

### PR DESCRIPTION
**Pull request by Gagaro**
Please see https://github.com/plone/mockup/pull/596

### CODE REVIEW

**Comment by vangheem** [comment]
tests running: http://jenkins.plone.org/job/pull-request-5.0/482/

**Comment by Gagaro** [comment]
I think there was a problem with travis.

**Comment by vangheem** [comment]
There was an error with the jenkins build too. Did you run the tests?

**Comment by Gagaro** [comment]
I did not, I looked at the failed tests.

**Comment by Gagaro** [comment]
Fixed by https://github.com/plone/plone.app.z3cform/pull/28

**Comment by mauritsvanrees** [comment]
There is a Jenkins failure in the robot tests. Can one of you check?
http://jenkins.plone.org/job/plone-5.0-python-2.7-robot/4158/robot/
http://jenkins.plone.org/job/plone-5.0-python-2.7-robot/4158/robot/report/

**Comment by Gagaro** [comment]
It doesn't seem related to this PR. Is there more change involved than this PR in those tests?

**Comment by mauritsvanrees** [comment]
Ah, it's green now after unrelated changes. Probably an unstable test. Never mind.

**Pull request merged**
