### PR TITLE
Fix RichTextWidget for non-contentish context

### PR DESCRIPTION
**Pull request by petschki**
see #161 
related to #160 but for 1.x branch (Plone 4.3 support)

### CODE REVIEW

**Comment by petschki** [comment]
@fredvd I've fixed your test issues in #158 with this pull request and picked your z3c.form fix too ... this bit me in the dx tests ... hope thats ok. @thet can you have a look at this? This obsoletes #158 ...

**Comment by petschki** [comment]
@fredvd @thet may I ping you regarding this one? I would really appreciate closing this and releasing 1.9.2 ... Would help me a lot getting collective.cover further to p.a.widgets ... Please let me know if there are any concerns ...

**Comment by thet** [comment]
looks very good to me. I'm merging.

**Comment by fredvd** [comment]
@petschki Ah, thanks for fixing the testing issues! I should get my notifications for github fixed, I think I disabled them all a long time ago because of the collective notifications.

**Comment by thet** [comment]
@fredvd I've set all to "watching" (but get the mails to a dedicated email address) https://gist.github.com/thet/c1ce413bdabc771cba1b

**Pull request merged**
