### PR TITLE
There is no profile to be registered

### PR DESCRIPTION
**Pull request by fulv**
Remove genericsetup:registerProfile zcml slug.

### CODE REVIEW

**Comment by ebrehault** [comment]
Tests: http://jenkins.plone.org/job/pull-request-5.0/515/

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/573

**Comment by gforcada** [comment]
Isn't this obsolete now that https://github.com/plone/plone.app.widgets/pull/121 has been merged?

**Comment by thet** [comment]
Oh, I didn't see this pull request. I also wanted to get rid of this dummy profile, but ``Products.ATContentTypes``, ``plone.app.collection`` and ``plone.app.relationfield`` (only in tests, IIRC) are installing it.
As long these packages are used in Plone 4 (they could...), we cannot remove the dummy profile from plone.app.widgets. If these packages are used in Plone 4, they need plone.app.widgets to be installed to work properly, therefore they need to install the plone.app.widgets 1.x profile, which is just a dummy profile in plone.app.widgets 2.x.

IMO, we can close this issue. Except we decide that the latest versions of the packages mentioned above shouldn't be used in Plone 4.

**Comment by jensens** [comment]
in 4.3:

- plone.app.collection is on 1.0.x branch
- Products.ATContentTypes is on 2.1.x branch
- plone.app.relationfield is not part of the core

**Pull request closed without merging**
