### PR TITLE
PLIP 2150

### PR DESCRIPTION
**Pull request by jensens**
branch by @thet - it is used in a customer project:

Change plone.app.widgets.utils.get_date_options and plone.widgets.utils.get_datetime_options to reflect settings of new pat-date-picker and pat-datetime-picker.

see https://github.com/plone/Products.CMFPlone/issues/2150

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
@petschki I think this should not be merged. The changes here are already in master.
I'd be happy if this branch can still exist a little longer, to check if we can just close it.

**Comment by petschki** [comment]
so you could safely close this PR and let the branch stay alive 🕺🏻

**Comment by jensens** [comment]
I created a simple branch protection so it wont get deleted accidentally and close this PR now.

**Pull request closed without merging**
